#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Labs
version:      1.1
version_from: lib/Acme/Labs.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
